language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

addons:
  code_climate:
    repo_token: 28c378564d788bca444a6a303cdb5f806d33b2c983ed59c1f43d66a37b0b3b45

install:
  - composer self-update
  - composer install --dev
script: phpunit --coverage-clover build/logs/clover.xml
after_script:
  - vendor/bin/test-reporter
